# Generated by Django 2.0.3 on 2018-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=32)),
                ('picture', models.CharField(max_length=700)),
                ('settings', models.CharField(max_length=5000)),
            ],
        ),
    ]
